name: "My action"
description: "Test my action"

inputs:
  message:
    description: "The message to print"
    required: true
    default: "hola"
  

runs:
  using: "composite"
  steps:
    - name: hola
      run: echo "hola ${{inputs.message}}"
      shell: bash