name: Test

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7 
      #- name: Script
      #  run: |
      #    chmod +x script.sh
      #    ./script.sh
  
      - name: ls
        run: ls -al
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: latest
      - name: node version
        run: node --version
      - name: Install
        run: npm install
      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: php version
        run: php --version

