name: Hola mundo

#on: [push, pull_request] #Este es el evento que espera que se ejecute 
on:
  push: # se especifica que evento se espera a ejecutar
    branches: # y espera a que rama afectara
      - main
  pull_request:
    branches:
      - main

jobs: #son los trabajos que se van a ejecutar
  hola: #el nombre del trabajo a ejecutar
    runs-on: ubuntu-latest #el SO donde se ejecutara
    steps: #pasos que seguir
      - name: hola mundo #pasos a seguir para ejecutar
        run: echo "Hola mundo" #run es para ejecutar comandos
      - name: touch file
        run: touch hola.txt 
      - name: Seet text
        run: echo "hola mundo" >> hola.txt
      - name: Read file
        run: cat hola.txt
  other:
    runs-on: ubuntu-latest
    needs: [hola] #Este es el job que necesita para ejecutar el job

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7     
      - name: LS
        run: ls -al

