name: Test strategy

on: [push]

jobs:
    local-action-strategy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: [7.4, 8.0, 8.1]
        
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{matrix.php-version}}

            - name: Run script
              run: |
                echo "PHP version ${{matrix.php-version}}"
                php -v