name: Ejemplo notificacion
on: [push]

jobs:
  local-action-notity:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          id: checkout
          uses: actions/checkout@v3

        - name: Notificacion
          uses: rtCamp/action-slack-notify@v2.1.1
          #succes(), failure(), alway()
          if: steps.checkout.outcome=='success'
          env:
            SLACK_WEBHOOK: ${{secrets.WEBHOOK_URL}}
          with:
            author_name: "Action"
            fields: repo, message, commit, author, action, eventName